server:
  port: 9090

spring:
  application:
    name: bus-provider
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
  cloud:
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
      trace:
        enabled: true
      ack:
        enabled: true
      id: provider-node1
      destination: "*" #bus-consumer-1

management:
  server:
    port: 9990
  endpoints:
    web:
      exposure:
        include: "*"

# 配置 Eureka Client（可参考 EurekaClientConfigBean）
eureka:
  client:
    service-url:
      defaultZone: 'http://127.0.0.1:12345/eureka'

topic:
  name: topic-1